name: build
on:
  push:
    branches:
      - develop
      - master
      - release-*
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        # TODO this should be setup by the CI machine?
        with:
          repositories: >
            [
              {
                "id": "bar",
                "name": "Bonita Artifact Repository",
                "url": "https://bonitasoft.jfrog.io/artifactory/maven",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          plugin_repositories: >
            [
              {
                "id": "bar",
                "name": "Bonita Artifact Repository",
                "url": "https://bonitasoft.jfrog.io/artifactory/maven",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              }
            ]
          servers: >
            [
              {
                "id": "bar",
                "username": "${{ secrets.JFROG_USER }}",
                "password": "${{ secrets.JFROG_TOKEN }}"
              }
            ]
      - name: Login to Docker internal registry
        uses: docker/login-action@v3
        with:
          registry: bonitasoft.jfrog.io
          username: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_TOKEN }}
      - name: Build
        run: ./mvnw clean package -Dbonita.environment=development -Pdocker -Ddocker.imageName=ghcr.io/rbioteau/sca-workshop:latest
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to docker
        run: docker push ghcr.io/rbioteau/sca-workshop:latest 